http_ip = "127.0.0.1"
http_port = 8000
ws_endpoint = "127.0.0.1:8001"
rpc_user = "bitcoin"
rpc_pass = "bitcoinrpc"

[coins.btc]
zmq_endpoint = "tcp://localhost:28332"

[coins.tbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "tb"
rpc_endpoint = "http://localhost:18332"
rest_endpoint = "http://localhost:18332/rest/"
zmq_endpoint = "tcp://localhost:28333"

[coins.rbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "bcrt"
rpc_endpoint = "http://localhost:18443"
rest_endpoint = "http://localhost:18443/rest/"
zmq_endpoint = "tcp://localhost:28334"

[coins.sbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "tb"
rpc_endpoint = "http://localhost:38332"
rest_endpoint = "http://localhost:38332/rest/"
zmq_endpoint = "tcp://localhost:28335"
