[coins.btc]
p2pkh_version = 0
p2sh_version = 5
segwit_hrp = "bc"
rpc_endpoint = "http://localhost:8332"
rpc_user = "bitcoin"
rpc_pass = "bitcoinrpc"
rest_endpoint = "http://localhost:8332/rest/"
zmq_endpoint = "tcp://localhost:28332"
http_ip = "127.0.0.1"
http_port = 6000
ws_endpoint = "127.0.0.1:7000"

[coins.tbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "tb"
rpc_endpoint = "http://localhost:18332"
rpc_user = "bitcoin"
rpc_pass = "bitcoinrpc"
rest_endpoint = "http://localhost:18332/rest/"
zmq_endpoint = "tcp://localhost:28333"
http_ip = "127.0.0.1"
http_port = 6001
ws_endpoint = "127.0.0.1:7001"

[coins.rbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "bcrt"
rpc_endpoint = "http://localhost:18443"
rpc_user = "bitcoin"
rpc_pass = "bitcoinrpc"
rest_endpoint = "http://localhost:18443/rest/"
zmq_endpoint = "tcp://localhost:28334"
http_ip = "127.0.0.1"
http_port = 6002
ws_endpoint = "127.0.0.1:7002"

[coins.sbtc]
p2pkh_version = 111
p2sh_version = 195
segwit_hrp = "tb"
rpc_endpoint = "http://localhost:38332"
rpc_user = "bitcoin"
rpc_pass = "bitcoinrpc"
rest_endpoint = "http://localhost:38332/rest/"
zmq_endpoint = "tcp://localhost:28335"
http_ip = "127.0.0.1"
http_port = 6003
ws_endpoint = "127.0.0.1:7003"
