name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CC: /tmp/sccache/sccache cc
  CXX: /tmp/sccache/sccache c++

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install -y libzmq3-dev

    - name: Configure sccache
      uses: visvirial/sccache-action@v1

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install criterion
      run: cargo install cargo-criterion

    - name: Run benchmark
      run: cargo criterion
