name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    env:
      SCCACHE_CACHE_SIZE: 512M
      CC: /tmp/sccache/sccache cc
      CXX: /tmp/sccache/sccache c++

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install -y libzmq3-dev

    - name: Configure sccache
      uses: visvirial/sccache-action@v1

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1

  doc:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install -y libzmq3-dev

    - name: Generate document
      run: cargo doc --verbose

    - name: Deploy document
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        cname: server-doc.chainseeker.info

